apiVersion: apps/v1
kind: Deployment
metadata:
   name: learningdevops
spec:
   selector:
     matchLabels:
       app: learningdevops
   replicas: 2
   strategy:
     type: RollingUpdate
     rollingUpdate:
       maxSurge: 1
       maxUnavailable: 1
      
   
   template:
     metadata:
       labels:
         app: learningdevops
     spec:
       containers:
       - name: learningdevops
         image: abhi144k/kubernetes
         imagePullPolicy: Always
         ports:
         - containerPort: 80        
            
